export const scopeHeaders = [
  {id:'SC_CB_Licensing_Code', title:'SC CB Licensing Code'},
  {id:'SC_No', title:'SC No'},
  {id:'SC_Version_No', title:'SC Version No'},
  {id:'SC_Status', title:'SC Status'},
  {id:'Certified_Organization_License_No', title:'Certified Organization License No'},
  {id:'Certified_Organization_Name', title:'Certified Organization Name'},
  {id:'Certified_Organization_Name_Native', title:'Certified Organization Name Native'},
  {id:'Certified_Organization_Contact_First_Name', title:'Certified Organization Contact First Name'},
  {id:'Certified_Organization_Contact_Last_Name', title:'Certified Organization Contact Last Name'},
  {id:'Certified_Organization_Email', title:'Certified Organization Email'},
  {id:'Certified_Organization_Website', title:'Certified Organization Website'},
  {id:'Certified_Organization_Public_Email', title:'Certified Organization Public Email'},
  {id:'Certified_Organization_Address_1', title:'Certified Organization Address 1'},
  {id:'Certified_Organization_Address_2', title:'Certified Organization Address 2'},
  {id:'Certified_Organization_Address_3', title:'Certified Organization Address 3'},
  {id:'Certified_Organization_Postcode', title:'Certified Organization Postcode'},
  {id:'Certified_Organization_Town', title:'Certified Organization Town'},
  {id:'Certified_Organization_State_Province', title:'Certified Organization State/Province'},
  {id:'Certified_Organization_Country_Area', title:'Certified Organization Country/Area'},
  {id:'SC_Standard_Program', title:'SC Standard Program'},
  {id:'SC_Standard', title:'SC Standard'},
  {id:'SC_Standard_Version', title:'SC Standard Version'},
  {id:'SC_Valid_Until', title:'SC Valid Until'},
  {id:'SC_Date_of_Issue', title:'SC Date of Issue'},
  {id:'SC_Place_of_Issue', title:'SC Place of Issue'},
  {id:'SC_Last_Updated', title:'SC Last Updated'},
  {id:'SC_CB_Accreditation_Body', title:'SC CB Accreditation Body'},
  {id:'SC_CB_Accreditation_No', title:'SC CB Accreditation No'},
  {id:'SC_CB_Inspection_Body', title:'SC CB Inspection Body'},
  {id:'SC_CB_Auditor_ID', title:'SC CB Auditor ID'},
  {id:'SC_CB_Scope_Stipulations', title:'SC CB Scope Stipulations'},
  {id:'Certified_Organization_Approved_Claims', title:'Certified Organization Approved Claims'},
  {id:'SC_Number_of_Farms', title:'SC Number of Farms'},
  {id:'Number_of_Audit_Days', title:'Number of Audit Days'},
  {id:'SC_Product_No', title:'SC Product No'},
  {id:'SC_Product_Category_Code', title:'SC Product Category Code'},
  {id:'SC_Product_Category_User_Specific_Term', title:'SC Product Category User Specific Term'},
  {id:'SC_Product_Detail_Code', title:'SC Product Detail Code'},
  {id:'SC_Product_Detail_User_Specific_Term', title:'SC Product Detail User Specific Term'},
  {id:'SC_Product_Standard_Label_Grade', title:'SC Product Standard (Label Grade)'},
  {id:'SC_Product_Raw_Material_Percentage', title:'SC Product Raw Material Percentage'},
  {id:'SC_Product_Raw_Material_Code', title:'SC Product Raw Material Code'},
  {id:'SC_Product_Raw_Material_User_Specific_Term', title:'SC Product Raw Material User Specific Term'},
  {id:'Facility_Type', title:'Facility Type'},
  {id:'Facility_No', title:'Facility No'},
  {id:'Facility_Subcontractor_License_No', title:'Facility Subcontractor License No'},
  {id:'Facility_OAR_ID', title:'Facility OAR ID'},
  {id:'Facility_Name', title:'Facility Name'},
  {id:'Facility_Address_1', title:'Facility Address 1'},
  {id:'Facility_Address_2', title:'Facility Address 2'},
  {id:'Facility_Address_3', title:'Facility Address 3'},
  {id:'Facility_Postcode', title:'Facility Postcode'},
  {id:'Facility_Town', title:'Facility Town'},
  {id:'Facility_State_Province', title:'Facility State/Province'},
  {id:'Facility_Country_Area', title:'Facility Country/Area'},
  {id:'Facility_CB_of_Independently_Certified_Subcontractor', title:'Facility CB of Independently Certified Subcontractor'},
  {id:'Facility_Expiry_Date_of_Independently_Certified_Subcontractor', title:'Facility Expiry Date of Independently Certified Subcontractor'},
  {id:'Facility_Process_Category_Code', title:'Facility Process Category Code'},
  {id:'Facility_Process_Category_User_Specific_Term', title:'Facility Process Category User Specific Term'},
  {id:'Facility_Standard', title:'Facility Standard'},
  {id:'Facility_Last_Audit_Date', title:'Facility Last Audit Date'},
  {id:'Facility_Farm_Capacity', title:'Facility Farm Capacity'},
]